# docker-compose.yml
version: '3.8'

services:
  api-gateway:
    build: ./services/api-gateway
    ports:
      - "8080:8080"
    environment:
      - QUERY_SERVICE_URL=http://query-service:8081
      - ANALYSIS_SERVICE_URL=http://analysis-service:8082
      - WEB_UI_URL=http://web-ui:3000
    depends_on:
      - query-service
      - analysis-service
      - web-ui

  query-service:
    build: ./services/query-service
    ports:
      - "8081:8081"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ./credentials.json:/app/credentials.json

  analysis-service:
    build: ./services/analysis-service
    ports:
      - "8082:8082"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}

  web-ui:
    build: ./services/web-ui
    ports:
      - "3000:3000"
    volumes:
      - ./static:/app/static